Implement solution and testing
nekotuko/problem-solving pull request #14
Opened 2023-10-14 23:44 UTC by frid-man

2023-10-14 23:49 UTC, frid-man commented on lc-0226-invert-binary-tree/src/test/java/solution/CustomCsvArgTest.java
> +public class CustomCsvArgTest {
I'm grouping generating binary tree List<Integer> from String and TreeNode in one static class. This works and I like keeping these together, but lmk if there's a better way to do this.

2023-10-17 08:20 UTC, suad-bakhshiyev commented on lc-0226-invert-binary-tree/src/test/java/solution/CustomCsvArgTest.java
> +    }
I'm grouping generating binary tree List from String and TreeNode in one static class. This works and I like keeping these together, but lmk if there's a better approach.

2023-10-17 08:20 UTC, suad-bakhshiyev commented on lc-0226-invert-binary-tree/src/test/java/solution/CustomCsvArgTest.java
> +public class CustomCsvArgTest {
I separated checking order of values and checking that the resulting tree is made of the original nodes in two separate tests, based on your past feedback.

2023-10-21 22:37 UTC, nekotuko requested changes

2023-10-21 22:37 UTC, nekotuko commented on lc-0226-invert-binary-tree/src/main/java/solution/Solution.java
> +            return null;
[missing { }](https://google.github.io/styleguide/javaguide.html)

2023-10-21 22:37 UTC, nekotuko commented on lc-0226-invert-binary-tree/src/test/java/solution/CustomCsvArgTest.java
> +            "[4,2,7,1,3,6,9]; [4,7,2,9,6,3,1]",
Maybe this can be easier to understand visually:
```
4->2, 4->7, 2->1, 2->3, ...
```

2023-10-21 22:37 UTC, nekotuko commented on lc-0226-invert-binary-tree/src/test/java/solution/CustomCsvArgTest.java
> +    static class MyTree {
Java forces classes on you, but I don't think you need a class here.

Try a method that takes a `String` and returns `TreeNode`. I think JUnit allows the use of factory methods, not just constructors for custom arguments.

2023-10-21 22:37 UTC, nekotuko commented on lc-0226-invert-binary-tree/src/test/java/solution/CustomCsvArgTest.java
> +    static class MyTree {
From [JUnit documentation](https://junit.org/junit5/docs/current/user-guide/#writing-tests-parameterized-tests-argument-conversion-implicit-fallback):

> factory method: a non-private, static method declared in the target type that accepts a single String argument and returns an instance of the target type. The name of the method can be arbitrary and need not follow any particular convention.

which means you can add a method to your real implementation (`TreeNode`).  The method can be something like:
```
public static TreeNode fromString(String str)
```
and JUnit will pick it up.

2023-10-21 22:37 UTC, nekotuko commented on lc-0226-invert-binary-tree/src/test/java/solution/CustomCsvArgTest.java
> +    }
This looks good!

2023-10-21 22:37 UTC, nekotuko commented on lc-0226-invert-binary-tree/src/test/java/solution/CustomCsvArgTest.java
> +    static class MyTree {
If you don't want to add this functionality to the real implementation, another approach is to do this:
```
static class TestTreeNode extends TreeNode {
    TestTreeNode(String s) {
        ...
    }
}
```
this way you can use `TestTreeNode` the same way as `TreeNode`, without having to access `.head` first.

2023-10-21 22:37 UTC, nekotuko commented on lc-0226-invert-binary-tree/src/test/java/solution/CustomCsvArgTest.java
> +            List<Integer> values = new MyTreeAsList(s).values;
This:
```
= new MyTreeAsList(s).values;
```
can almost always can be replaced with:
```
= TestUtils.toList(s);
```

In other words, if you only constuct a class (e.g. `MyTreeAsList`) to get its guts and throw it away, you don't need that class. A function will be more appropriate.

2023-10-21 22:37 UTC, nekotuko commented on lc-0226-invert-binary-tree/src/test/java/solution/CustomCsvArgTest.java
> +            if (values.isEmpty() || (values.size() == 1 && values.get(0) == null)) {
Unless I'm missing something, this can be simplified to:
```
if (values.isEmpty() || values.get(0) == null)
```

2023-10-21 22:37 UTC, nekotuko commented on lc-0226-invert-binary-tree/src/test/java/solution/CustomCsvArgTest.java
> +public class CustomCsvArgTest {
This looks good. Good job!

2024-03-09 20:46 UTC, nekotuko approved these changes

2024-03-09 20:55 UTC, nekotuko approved these changes

2024-03-09 20:55 UTC, merged